server:
  port: 8011
  servlet:
    context-path: /garage

spring:
  application:
    name: garage
  data:
    jpa.repositories.enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/garage
    username: postgres
    password: postgres
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 10000
    driver-class-name: org.postgresql.Driver
    initialization-mode: embedded
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: false
        jdbc:
          lob:
            non-contextual-creation: true
        temp:
          use_jdbc_metadata_defaults: false
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  file:
    path: logs

---

spring:
  profiles: dev

---

spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/garage
    username: postgres
    password: postgres

---

spring:
  profiles: prod
